export enum ActionTypes {
  FETCH_MOVIE = 'FETCH_MOVIE',
  FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS',
  FETCH_MOVIE_FAILURE = 'FETCH_MOVIE_FAILURE',
  FETCH_MOVIE_INFO = 'FETCH_MOVIE_INFO',
  FETCH_MOVIE_INFO_SUCCESS = 'FETCH_MOVIE_INFO_SUCCESS',
  FETCH_MOVIE_INFO_FAILURE = 'FETCH_MOVIE_INFO_FAILURE',
}
